// Beginner-tier diagnostic quiz pool: real chess positions, not text
// trivia. Every position was generated and legality-checked
// programmatically (kings present, not adjacent, no side illegally in
// check), and every correct answer was computed directly from the
// position by code (piece identification, square color parity, legal
// move counts, attacked and undefended piece detection, pawn
// promotion eligibility) rather than asserted by hand. At this volume,
// verification by computation is more reliable than eyeballing each
// position individually. The generator itself was unit-tested against
// known correct values (a rook in a corner has exactly 14 empty-board
// moves, a queen in the center has exactly 27, and so on) before being
// used to produce this pool.
export const DIAGNOSTIC_BEGINNER_POOL = [
  {
    id: "pool-identify-1",
    cat: "rules",
    prompt: "What piece is on e7 in this position?",
    fen: "8/k3N3/8/8/8/3K4/8/8 w - - 0 1",
    options: ["Bishop", "Rook", "Pawn", "Knight"],
    answer: 3,
  },
  {
    id: "pool-squarecolor-2",
    cat: "rules",
    prompt: "What color is the square e1?",
    fen: "3K4/6k1/8/8/8/8/8/8 w - - 0 1",
    options: ["Light", "Dark"],
    answer: 1,
  },
  {
    id: "pool-mobility-3",
    cat: "rules",
    prompt: "From this position, how many legal squares can the white bishop on g3 move to?",
    fen: "8/8/8/2K5/8/6B1/8/5k2 w - - 0 1",
    options: ["7", "3", "9", "11"],
    answer: 2,
  },
  {
    id: "pool-hanging-4",
    cat: "tactics",
    prompt: "One piece on the board is attacked and has no defender. Which square is it on?",
    fen: "1r4K1/8/8/3R4/4q2k/3p4/8/8 w - - 0 1",
    options: ["b8", "d5", "d3", "e4"],
    answer: 1,
  },
  {
    id: "pool-promotion-5",
    cat: "endgame",
    prompt: "Can the White pawn on e7 promote by moving straight forward one square?",
    fen: "7K/4P3/8/k7/8/8/8/8 w - - 0 1",
    options: ["No", "Yes"],
    answer: 1,
  },
  {
    id: "pool-mostactive-6",
    cat: "positional",
    prompt: "Of the three white pieces on the board, which one currently has the most legal moves available?",
    fen: "8/1k6/1N6/8/7Q/3KQ3/8/8 w - - 0 1",
    options: ["b6", "h4", "e3"],
    answer: 1,
  },
  {
    id: "pool-identify-7",
    cat: "rules",
    prompt: "What piece is on h2 in this position?",
    fen: "3k4/8/8/8/8/8/7p/7K w - - 0 1",
    options: ["Knight", "Rook", "Pawn", "Bishop"],
    answer: 2,
  },
  {
    id: "pool-squarecolor-8",
    cat: "rules",
    prompt: "What color is the square d5?",
    fen: "6K1/8/8/8/3k4/8/8/8 w - - 0 1",
    options: ["Light", "Dark"],
    answer: 0,
  },
  {
    id: "pool-mobility-9",
    cat: "rules",
    prompt: "From this position, how many legal squares can the white queen on a6 move to?",
    fen: "8/8/Q7/8/1k6/8/7K/8 w - - 0 1",
    options: ["15", "21", "17", "19"],
    answer: 1,
  },
  {
    id: "pool-hanging-10",
    cat: "tactics",
    prompt: "One piece on the board is attacked and has no defender. Which square is it on?",
    fen: "8/5R2/5K2/8/2k5/8/8/r4N1b w - - 0 1",
    options: ["f7", "h1", "a1", "f1"],
    answer: 3,
  },
  {
    id: "pool-promotion-11",
    cat: "endgame",
    prompt: "Can the White pawn on h7 promote by moving straight forward one square?",
    fen: "8/7P/5K2/8/8/8/7k/8 w - - 0 1",
    options: ["No", "Yes"],
    answer: 1,
  },
  {
    id: "pool-mostactive-12",
    cat: "positional",
    prompt: "Of the three white pieces on the board, which one currently has the most legal moves available?",
    fen: "K2R4/8/8/8/8/5k2/4N3/7R w - - 0 1",
    options: ["h1", "d8", "e2"],
    answer: 0,
  },
  {
    id: "pool-identify-13",
    cat: "rules",
    prompt: "What piece is on c1 in this position?",
    fen: "8/8/5k2/8/8/1K6/8/2N5 w - - 0 1",
    options: ["Bishop", "Pawn", "Knight", "Rook"],
    answer: 2,
  },
  {
    id: "pool-squarecolor-14",
    cat: "rules",
    prompt: "What color is the square b3?",
    fen: "3k4/8/8/8/8/8/7K/8 w - - 0 1",
    options: ["Light", "Dark"],
    answer: 0,
  },
  {
    id: "pool-mobility-15",
    cat: "rules",
    prompt: "From this position, how many legal squares can the white knight on f3 move to?",
    fen: "8/8/8/8/6k1/1K3N2/8/8 w - - 0 1",
    options: ["8", "2", "14", "10"],
    answer: 0,
  },
  {
    id: "pool-hanging-16",
    cat: "tactics",
    prompt: "One piece on the board is attacked and has no defender. Which square is it on?",
    fen: "7P/r7/2k5/8/8/1r2K3/8/q2n4 w - - 0 1",
    options: ["a1", "h8", "d1", "b3"],
    answer: 1,
  },
  {
    id: "pool-promotion-17",
    cat: "endgame",
    prompt: "Can the Black pawn on e2 promote by moving straight forward one square?",
    fen: "1K6/8/8/8/8/7k/4p3/8 b - - 0 1",
    options: ["No", "Yes"],
    answer: 1,
  },
  {
    id: "pool-mostactive-18",
    cat: "positional",
    prompt: "Of the three white pieces on the board, which one currently has the most legal moves available?",
    fen: "6k1/7N/8/8/Q7/3N4/5K2/8 w - - 0 1",
    options: ["d3", "a4", "h7"],
    answer: 1,
  },
  {
    id: "pool-identify-19",
    cat: "rules",
    prompt: "What piece is on h1 in this position?",
    fen: "K7/8/8/1k6/8/8/8/7Q w - - 0 1",
    options: ["Knight", "Pawn", "Queen", "Bishop"],
    answer: 2,
  },
  {
    id: "pool-squarecolor-20",
    cat: "rules",
    prompt: "What color is the square d7?",
    fen: "3K4/8/k7/8/8/8/8/8 w - - 0 1",
    options: ["Light", "Dark"],
    answer: 0,
  },
  {
    id: "pool-mobility-21",
    cat: "rules",
    prompt: "From this position, how many legal squares can the white queen on d3 move to?",
    fen: "8/8/8/8/5k2/K2Q4/8/8 w - - 0 1",
    options: ["24", "22", "18", "26"],
    answer: 0,
  },
  {
    id: "pool-hanging-22",
    cat: "tactics",
    prompt: "One piece on the board is attacked and has no defender. Which square is it on?",
    fen: "8/3R4/2K4p/6N1/8/3N4/8/3k4 w - - 0 1",
    options: ["d7", "d3", "g5", "h6"],
    answer: 2,
  },
  {
    id: "pool-promotion-23",
    cat: "endgame",
    prompt: "Can the Black pawn on b2 promote by moving straight forward one square?",
    fen: "8/2k5/8/8/K7/8/1p6/1R6 b - - 0 1",
    options: ["Yes", "No"],
    answer: 1,
  },
  {
    id: "pool-mostactive-24",
    cat: "positional",
    prompt: "Of the three white pieces on the board, which one currently has the most legal moves available?",
    fen: "8/8/1K6/8/5k2/3R4/8/1N1R4 w - - 0 1",
    options: ["d3", "b1", "d1"],
    answer: 0,
  },
  {
    id: "pool-identify-25",
    cat: "rules",
    prompt: "What piece is on a1 in this position?",
    fen: "8/8/8/k7/8/8/8/r6K w - - 0 1",
    options: ["Queen", "Rook", "Knight", "Bishop"],
    answer: 1,
  },
  {
    id: "pool-squarecolor-26",
    cat: "rules",
    prompt: "What color is the square g5?",
    fen: "8/1k6/8/8/8/8/3K4/8 w - - 0 1",
    options: ["Light", "Dark"],
    answer: 1,
  },
  {
    id: "pool-hanging-28",
    cat: "tactics",
    prompt: "One piece on the board is attacked and has no defender. Which square is it on?",
    fen: "r3n1P1/8/8/2K4N/2p5/5k2/8/8 w - - 0 1",
    options: ["e8", "g8", "c4", "h5"],
    answer: 2,
  },
  {
    id: "pool-promotion-29",
    cat: "endgame",
    prompt: "Can the Black pawn on a2 promote by moving straight forward one square?",
    fen: "8/8/8/2K5/7k/8/p7/8 b - - 0 1",
    options: ["Yes", "No"],
    answer: 0,
  },
  {
    id: "pool-mostactive-30",
    cat: "positional",
    prompt: "Of the three white pieces on the board, which one currently has the most legal moves available?",
    fen: "2B5/8/3R4/8/3K4/k7/8/1B6 w - - 0 1",
    options: ["d6", "c8", "b1"],
    answer: 0,
  },
  {
    id: "pool-identify-31",
    cat: "rules",
    prompt: "What piece is on g1 in this position?",
    fen: "4K3/8/8/8/8/8/8/4k1B1 w - - 0 1",
    options: ["Queen", "Bishop", "Knight", "Rook"],
    answer: 1,
  },
  {
    id: "pool-squarecolor-32",
    cat: "rules",
    prompt: "What color is the square d4?",
    fen: "8/8/8/8/1k6/8/4K3/8 w - - 0 1",
    options: ["Light", "Dark"],
    answer: 1,
  },
  {
    id: "pool-mobility-33",
    cat: "rules",
    prompt: "From this position, how many legal squares can the white queen on e5 move to?",
    fen: "8/8/1k6/4Q3/7K/8/8/8 w - - 0 1",
    options: ["23", "31", "27", "21"],
    answer: 2,
  },
  {
    id: "pool-hanging-34",
    cat: "tactics",
    prompt: "One piece on the board is attacked and has no defender. Which square is it on?",
    fen: "8/8/8/q7/k5pQ/2p5/3K2B1/8 w - - 0 1",
    options: ["g4", "c3", "h4", "a5"],
    answer: 0,
  },
  {
    id: "pool-promotion-35",
    cat: "endgame",
    prompt: "Can the White pawn on e7 promote by moving straight forward one square?",
    fen: "2k5/4P3/8/8/2K5/8/8/8 w - - 0 1",
    options: ["No", "Yes"],
    answer: 1,
  },
  {
    id: "pool-mostactive-36",
    cat: "positional",
    prompt: "Of the three white pieces on the board, which one currently has the most legal moves available?",
    fen: "1K6/8/3Bk3/2B5/7R/8/8/8 w - - 0 1",
    options: ["d6", "h4", "c5"],
    answer: 1,
  },
  {
    id: "pool-identify-37",
    cat: "rules",
    prompt: "What piece is on f5 in this position?",
    fen: "8/8/8/5P2/1K6/5k2/8/8 w - - 0 1",
    options: ["Pawn", "Queen", "Knight", "Rook"],
    answer: 0,
  },
  {
    id: "pool-squarecolor-38",
    cat: "rules",
    prompt: "What color is the square b4?",
    fen: "8/8/8/1K6/6k1/8/8/8 w - - 0 1",
    options: ["Dark", "Light"],
    answer: 0,
  },
  {
    id: "pool-mobility-39",
    cat: "rules",
    prompt: "From this position, how many legal squares can the white knight on a7 move to?",
    fen: "8/N7/8/8/k7/8/7K/8 w - - 0 1",
    options: ["5", "3", "1", "9"],
    answer: 1,
  },
  {
    id: "pool-hanging-40",
    cat: "tactics",
    prompt: "One piece on the board is attacked and has no defender. Which square is it on?",
    fen: "8/8/1K2r3/5k2/8/2n5/1R6/2Q5 w - - 0 1",
    options: ["c1", "e6", "c3", "b2"],
    answer: 2,
  },
  {
    id: "pool-promotion-41",
    cat: "endgame",
    prompt: "Can the White pawn on h7 promote by moving straight forward one square?",
    fen: "8/7P/8/4k3/8/K7/8/8 w - - 0 1",
    options: ["No", "Yes"],
    answer: 1,
  },
  {
    id: "pool-mostactive-42",
    cat: "positional",
    prompt: "Of the three white pieces on the board, which one currently has the most legal moves available?",
    fen: "8/8/2R5/8/k5K1/8/4B2N/8 w - - 0 1",
    options: ["c6", "e2", "h2"],
    answer: 0,
  },
  {
    id: "pool-identify-43",
    cat: "rules",
    prompt: "What piece is on g3 in this position?",
    fen: "8/8/2K5/8/8/6N1/1k6/8 w - - 0 1",
    options: ["Queen", "Knight", "Pawn", "Rook"],
    answer: 1,
  },
  {
    id: "pool-squarecolor-44",
    cat: "rules",
    prompt: "What color is the square c8?",
    fen: "8/8/1k6/8/6K1/8/8/8 w - - 0 1",
    options: ["Light", "Dark"],
    answer: 0,
  },
  {
    id: "pool-hanging-46",
    cat: "tactics",
    prompt: "One piece on the board is attacked and has no defender. Which square is it on?",
    fen: "7k/8/8/8/1Q2B3/4KQ2/8/3p4 w - - 0 1",
    options: ["f3", "e4", "b4", "d1"],
    answer: 3,
  },
  {
    id: "pool-promotion-47",
    cat: "endgame",
    prompt: "Can the White pawn on c7 promote by moving straight forward one square?",
    fen: "K7/2Pk4/8/8/8/8/8/8 w - - 0 1",
    options: ["No", "Yes"],
    answer: 1,
  },
  {
    id: "pool-mostactive-48",
    cat: "positional",
    prompt: "Of the three white pieces on the board, which one currently has the most legal moves available?",
    fen: "8/8/K7/8/8/8/N5kN/4B3 w - - 0 1",
    options: ["e1", "a2", "h2"],
    answer: 0,
  },
  {
    id: "pool-identify-49",
    cat: "rules",
    prompt: "What piece is on e1 in this position?",
    fen: "8/8/8/K7/8/7k/8/4n3 w - - 0 1",
    options: ["Knight", "Pawn", "Bishop", "Rook"],
    answer: 0,
  },
  {
    id: "pool-squarecolor-50",
    cat: "rules",
    prompt: "What color is the square f5?",
    fen: "8/8/8/8/8/8/k7/7K w - - 0 1",
    options: ["Dark", "Light"],
    answer: 1,
  },
  {
    id: "pool-mobility-51",
    cat: "rules",
    prompt: "From this position, how many legal squares can the white bishop on h6 move to?",
    fen: "8/8/6KB/8/8/5k2/8/8 w - - 0 1",
    options: ["7", "11", "13", "9"],
    answer: 0,
  },
  {
    id: "pool-hanging-52",
    cat: "tactics",
    prompt: "One piece on the board is attacked and has no defender. Which square is it on?",
    fen: "8/8/q7/1K1n3k/Q5q1/6n1/8/8 w - - 0 1",
    options: ["g4", "a6", "g3", "d5"],
    answer: 1,
  },
  {
    id: "pool-promotion-53",
    cat: "endgame",
    prompt: "Can the Black pawn on e2 promote by moving straight forward one square?",
    fen: "8/4k3/8/1K6/8/8/4p3/4B3 b - - 0 1",
    options: ["Yes", "No"],
    answer: 1,
  },
  {
    id: "pool-mostactive-54",
    cat: "positional",
    prompt: "Of the three white pieces on the board, which one currently has the most legal moves available?",
    fen: "8/8/k7/8/7R/1B6/8/3KR3 w - - 0 1",
    options: ["h4", "b3", "e1"],
    answer: 0,
  },
  {
    id: "pool-identify-55",
    cat: "rules",
    prompt: "What piece is on e5 in this position?",
    fen: "1K6/5k2/8/4B3/8/8/8/8 w - - 0 1",
    options: ["Pawn", "Knight", "Bishop", "Queen"],
    answer: 2,
  },
  {
    id: "pool-squarecolor-56",
    cat: "rules",
    prompt: "What color is the square h6?",
    fen: "8/4k3/8/8/2K5/8/8/8 w - - 0 1",
    options: ["Dark", "Light"],
    answer: 0,
  },
  {
    id: "pool-mobility-57",
    cat: "rules",
    prompt: "From this position, how many legal squares can the white knight on e2 move to?",
    fen: "8/8/8/7k/8/8/4N1K1/8 w - - 0 1",
    options: ["10", "6", "0", "12"],
    answer: 1,
  },
  {
    id: "pool-hanging-58",
    cat: "tactics",
    prompt: "One piece on the board is attacked and has no defender. Which square is it on?",
    fen: "8/5N2/1k4r1/8/7K/6R1/8/4R3 w - - 0 1",
    options: ["e1", "g6", "g3", "f7"],
    answer: 1,
  },
  {
    id: "pool-promotion-59",
    cat: "endgame",
    prompt: "Can the White pawn on a7 promote by moving straight forward one square?",
    fen: "q7/P2k4/8/8/8/8/8/6K1 w - - 0 1",
    options: ["No", "Yes"],
    answer: 0,
  },
  {
    id: "pool-mostactive-60",
    cat: "positional",
    prompt: "Of the three white pieces on the board, which one currently has the most legal moves available?",
    fen: "R7/5Q2/7B/8/8/8/3K4/7k w - - 0 1",
    options: ["h6", "a8", "f7"],
    answer: 2,
  },
  {
    id: "pool-identify-61",
    cat: "rules",
    prompt: "What piece is on b4 in this position?",
    fen: "8/8/8/3k4/1P6/8/8/4K3 w - - 0 1",
    options: ["Knight", "Queen", "Pawn", "Rook"],
    answer: 2,
  },
  {
    id: "pool-squarecolor-62",
    cat: "rules",
    prompt: "What color is the square a4?",
    fen: "3k4/8/8/8/3K4/8/8/8 w - - 0 1",
    options: ["Dark", "Light"],
    answer: 1,
  },
  {
    id: "pool-mobility-63",
    cat: "rules",
    prompt: "From this position, how many legal squares can the white rook on h7 move to?",
    fen: "8/7R/2k5/8/8/5K2/8/8 w - - 0 1",
    options: ["14", "8", "16", "10"],
    answer: 0,
  },
  {
    id: "pool-hanging-64",
    cat: "tactics",
    prompt: "One piece on the board is attacked and has no defender. Which square is it on?",
    fen: "8/8/2N2K2/8/6R1/1P5k/5P2/P7 w - - 0 1",
    options: ["f2", "g4", "b3", "a1"],
    answer: 1,
  },
  {
    id: "pool-promotion-65",
    cat: "endgame",
    prompt: "Can the White pawn on g7 promote by moving straight forward one square?",
    fen: "8/6P1/8/8/8/K7/4k3/8 w - - 0 1",
    options: ["Yes", "No"],
    answer: 0,
  },
  {
    id: "pool-mostactive-66",
    cat: "positional",
    prompt: "Of the three white pieces on the board, which one currently has the most legal moves available?",
    fen: "1N6/1Q6/8/5K2/2k5/8/1B6/8 w - - 0 1",
    options: ["b7", "b2", "b8"],
    answer: 0,
  },
  {
    id: "pool-identify-67",
    cat: "rules",
    prompt: "What piece is on c3 in this position?",
    fen: "8/8/1K6/6k1/8/2r5/8/8 w - - 0 1",
    options: ["Queen", "Rook", "Bishop", "Pawn"],
    answer: 1,
  },
  {
    id: "pool-squarecolor-68",
    cat: "rules",
    prompt: "What color is the square e7?",
    fen: "8/8/8/8/6k1/8/K7/8 w - - 0 1",
    options: ["Dark", "Light"],
    answer: 0,
  },
  {
    id: "pool-mobility-69",
    cat: "rules",
    prompt: "From this position, how many legal squares can the white bishop on c6 move to?",
    fen: "7k/8/2B5/7K/8/8/8/8 w - - 0 1",
    options: ["11", "13", "7", "17"],
    answer: 0,
  },
  {
    id: "pool-hanging-70",
    cat: "tactics",
    prompt: "One piece on the board is attacked and has no defender. Which square is it on?",
    fen: "8/4R2R/k7/8/4q3/1K6/5b2/8 w - - 0 1",
    options: ["e7", "h7", "e4", "f2"],
    answer: 2,
  },
  {
    id: "pool-promotion-71",
    cat: "endgame",
    prompt: "Can the White pawn on d7 promote by moving straight forward one square?",
    fen: "3nK3/3P4/8/2k5/8/8/8/8 w - - 0 1",
    options: ["No", "Yes"],
    answer: 0,
  },
  {
    id: "pool-mostactive-72",
    cat: "positional",
    prompt: "Of the three white pieces on the board, which one currently has the most legal moves available?",
    fen: "8/8/1k6/2R5/8/3B4/1K5R/8 w - - 0 1",
    options: ["d3", "c5", "h2"],
    answer: 1,
  },
  {
    id: "pool-squarecolor-74",
    cat: "rules",
    prompt: "What color is the square f8?",
    fen: "8/7k/8/3K4/8/8/8/8 w - - 0 1",
    options: ["Light", "Dark"],
    answer: 1,
  },
  {
    id: "pool-mobility-75",
    cat: "rules",
    prompt: "From this position, how many legal squares can the white rook on d8 move to?",
    fen: "3R4/7K/8/8/8/8/8/5k2 w - - 0 1",
    options: ["14", "10", "20", "18"],
    answer: 0,
  },
  {
    id: "pool-hanging-76",
    cat: "tactics",
    prompt: "One piece on the board is attacked and has no defender. Which square is it on?",
    fen: "8/8/6B1/8/Kq6/8/5n2/b5k1 w - - 0 1",
    options: ["a1", "g6", "b4", "f2"],
    answer: 2,
  },
  {
    id: "pool-mostactive-78",
    cat: "positional",
    prompt: "Of the three white pieces on the board, which one currently has the most legal moves available?",
    fen: "3K4/4R3/1R6/1B1k4/8/8/8/8 w - - 0 1",
    options: ["e7", "b5", "b6"],
    answer: 0,
  },
  {
    id: "pool-squarecolor-80",
    cat: "rules",
    prompt: "What color is the square c5?",
    fen: "K7/7k/8/8/8/8/8/8 w - - 0 1",
    options: ["Light", "Dark"],
    answer: 1,
  },
  {
    id: "pool-mobility-81",
    cat: "rules",
    prompt: "From this position, how many legal squares can the white bishop on g4 move to?",
    fen: "1K6/8/8/8/6B1/8/8/k7 w - - 0 1",
    options: ["15", "3", "11", "9"],
    answer: 3,
  },
  {
    id: "pool-hanging-82",
    cat: "tactics",
    prompt: "One piece on the board is attacked and has no defender. Which square is it on?",
    fen: "8/8/8/1q2r1k1/8/5p2/5R1K/8 w - - 0 1",
    options: ["f3", "b5", "e5", "f2"],
    answer: 0,
  },
  {
    id: "pool-promotion-83",
    cat: "endgame",
    prompt: "Can the Black pawn on e2 promote by moving straight forward one square?",
    fen: "8/8/7k/8/8/8/4p3/K3R3 b - - 0 1",
    options: ["Yes", "No"],
    answer: 1,
  },
  {
    id: "pool-mostactive-84",
    cat: "positional",
    prompt: "Of the three white pieces on the board, which one currently has the most legal moves available?",
    fen: "7K/4R3/8/B7/7k/8/8/1B6 w - - 0 1",
    options: ["b1", "e7", "a5"],
    answer: 1,
  },
  {
    id: "pool-identify-85",
    cat: "rules",
    prompt: "What piece is on f5 in this position?",
    fen: "8/8/8/5N2/8/8/1k3K2/8 w - - 0 1",
    options: ["Knight", "Bishop", "Rook", "Queen"],
    answer: 0,
  },
  {
    id: "pool-squarecolor-86",
    cat: "rules",
    prompt: "What color is the square c3?",
    fen: "k7/6K1/8/8/8/8/8/8 w - - 0 1",
    options: ["Light", "Dark"],
    answer: 1,
  },
  {
    id: "pool-mobility-87",
    cat: "rules",
    prompt: "From this position, how many legal squares can the white rook on f5 move to?",
    fen: "5K2/8/8/5R2/8/8/3k4/8 w - - 0 1",
    options: ["11", "7", "13", "9"],
    answer: 2,
  },
  {
    id: "pool-hanging-88",
    cat: "tactics",
    prompt: "One piece on the board is attacked and has no defender. Which square is it on?",
    fen: "1k3Nb1/6P1/8/8/8/8/5K2/6p1 w - - 0 1",
    options: ["f8", "g1", "g8", "g7"],
    answer: 1,
  },
  {
    id: "pool-promotion-89",
    cat: "endgame",
    prompt: "Can the Black pawn on h2 promote by moving straight forward one square?",
    fen: "8/8/1k6/8/8/8/2K4p/7Q b - - 0 1",
    options: ["No", "Yes"],
    answer: 0,
  },
  {
    id: "pool-mostactive-90",
    cat: "positional",
    prompt: "Of the three white pieces on the board, which one currently has the most legal moves available?",
    fen: "k7/8/3K4/2Q5/7N/3N4/8/8 w - - 0 1",
    options: ["d3", "c5", "h4"],
    answer: 1,
  },
  {
    id: "pool-identify-91",
    cat: "rules",
    prompt: "What piece is on a5 in this position?",
    fen: "8/8/2K5/r7/8/8/3k4/8 w - - 0 1",
    options: ["Rook", "Bishop", "Queen", "Knight"],
    answer: 0,
  },
  {
    id: "pool-squarecolor-92",
    cat: "rules",
    prompt: "What color is the square h8?",
    fen: "8/8/8/8/8/8/k7/3K4 w - - 0 1",
    options: ["Light", "Dark"],
    answer: 1,
  },
  {
    id: "pool-hanging-94",
    cat: "tactics",
    prompt: "One piece on the board is attacked and has no defender. Which square is it on?",
    fen: "8/7K/8/8/6k1/R2B4/6q1/5bR1 w - - 0 1",
    options: ["g1", "f1", "d3", "g2"],
    answer: 0,
  },
  {
    id: "pool-promotion-95",
    cat: "endgame",
    prompt: "Can the Black pawn on a2 promote by moving straight forward one square?",
    fen: "8/1k6/8/8/8/8/pK6/Q7 b - - 0 1",
    options: ["Yes", "No"],
    answer: 1,
  },
  {
    id: "pool-mostactive-96",
    cat: "positional",
    prompt: "Of the three white pieces on the board, which one currently has the most legal moves available?",
    fen: "8/8/6K1/2N2B2/8/5B2/7k/8 w - - 0 1",
    options: ["f5", "c5", "f3"],
    answer: 2,
  },
  {
    id: "pool-identify-97",
    cat: "rules",
    prompt: "What piece is on a5 in this position?",
    fen: "8/8/8/pk6/8/8/5K2/8 w - - 0 1",
    options: ["Pawn", "Rook", "Knight", "Bishop"],
    answer: 0,
  },
  {
    id: "pool-squarecolor-98",
    cat: "rules",
    prompt: "What color is the square a4?",
    fen: "8/7k/8/8/5K2/8/8/8 w - - 0 1",
    options: ["Dark", "Light"],
    answer: 1,
  },
  {
    id: "pool-mobility-99",
    cat: "rules",
    prompt: "From this position, how many legal squares can the white rook on h7 move to?",
    fen: "8/6KR/8/8/8/8/8/k7 w - - 0 1",
    options: ["3", "7", "11", "9"],
    answer: 1,
  },
  {
    id: "pool-hanging-100",
    cat: "tactics",
    prompt: "One piece on the board is attacked and has no defender. Which square is it on?",
    fen: "3q4/1p6/1K6/Q7/8/8/2k5/4R2q w - - 0 1",
    options: ["h1", "b7", "e1", "a5"],
    answer: 0,
  },
  {
    id: "pool-promotion-101",
    cat: "endgame",
    prompt: "Can the White pawn on e7 promote by moving straight forward one square?",
    fen: "4q2k/4P3/8/6K1/8/8/8/8 w - - 0 1",
    options: ["Yes", "No"],
    answer: 1,
  },
  {
    id: "pool-mostactive-102",
    cat: "positional",
    prompt: "Of the three white pieces on the board, which one currently has the most legal moves available?",
    fen: "7K/8/2k5/8/7R/8/N7/2B5 w - - 0 1",
    options: ["a2", "c1", "h4"],
    answer: 2,
  },
  {
    id: "pool-identify-103",
    cat: "rules",
    prompt: "What piece is on f3 in this position?",
    fen: "8/4K3/8/8/8/3k1r2/8/8 w - - 0 1",
    options: ["Bishop", "Knight", "Pawn", "Rook"],
    answer: 3,
  },
  {
    id: "pool-squarecolor-104",
    cat: "rules",
    prompt: "What color is the square b1?",
    fen: "8/8/8/8/8/8/5k2/2K5 w - - 0 1",
    options: ["Light", "Dark"],
    answer: 0,
  },
  {
    id: "pool-mobility-105",
    cat: "rules",
    prompt: "From this position, how many legal squares can the white rook on b3 move to?",
    fen: "k7/8/8/1K6/8/1R6/8/8 w - - 0 1",
    options: ["4", "8", "16", "10"],
    answer: 3,
  },
  {
    id: "pool-hanging-106",
    cat: "tactics",
    prompt: "One piece on the board is attacked and has no defender. Which square is it on?",
    fen: "8/8/4Q3/2K5/5Nb1/8/3Q4/1k6 w - - 0 1",
    options: ["e6", "f4", "d2", "g4"],
    answer: 3,
  },
  {
    id: "pool-promotion-107",
    cat: "endgame",
    prompt: "Can the White pawn on h7 promote by moving straight forward one square?",
    fen: "4k2p/7P/8/8/8/8/5K2/8 w - - 0 1",
    options: ["No", "Yes"],
    answer: 0,
  },
  {
    id: "pool-mostactive-108",
    cat: "positional",
    prompt: "Of the three white pieces on the board, which one currently has the most legal moves available?",
    fen: "8/7K/6R1/2k4B/8/8/B7/8 w - - 0 1",
    options: ["a2", "h5", "g6"],
    answer: 2,
  },
  {
    id: "pool-identify-109",
    cat: "rules",
    prompt: "What piece is on d8 in this position?",
    fen: "3N4/8/8/8/8/2k4K/8/8 w - - 0 1",
    options: ["Knight", "Bishop", "Rook", "Pawn"],
    answer: 0,
  },
  {
    id: "pool-squarecolor-110",
    cat: "rules",
    prompt: "What color is the square a5?",
    fen: "3k4/8/8/8/8/1K6/8/8 w - - 0 1",
    options: ["Dark", "Light"],
    answer: 0,
  },
  {
    id: "pool-mobility-111",
    cat: "rules",
    prompt: "From this position, how many legal squares can the white rook on e8 move to?",
    fen: "4R3/8/7K/8/8/8/8/7k w - - 0 1",
    options: ["10", "12", "14", "20"],
    answer: 2,
  },
  {
    id: "pool-hanging-112",
    cat: "tactics",
    prompt: "One piece on the board is attacked and has no defender. Which square is it on?",
    fen: "8/n7/3R4/3K4/2r5/6k1/r7/8 w - - 0 1",
    options: ["a2", "c4", "d6", "a7"],
    answer: 1,
  },
  {
    id: "pool-promotion-113",
    cat: "endgame",
    prompt: "Can the Black pawn on d2 promote by moving straight forward one square?",
    fen: "8/8/8/3K4/8/8/3p2k1/8 b - - 0 1",
    options: ["No", "Yes"],
    answer: 1,
  },
  {
    id: "pool-mostactive-114",
    cat: "positional",
    prompt: "Of the three white pieces on the board, which one currently has the most legal moves available?",
    fen: "8/6k1/2K5/8/3R4/4N3/8/1N6 w - - 0 1",
    options: ["e3", "b1", "d4"],
    answer: 2,
  },
  {
    id: "pool-identify-115",
    cat: "rules",
    prompt: "What piece is on a5 in this position?",
    fen: "8/7K/8/nk6/8/8/8/8 w - - 0 1",
    options: ["Bishop", "Queen", "Knight", "Rook"],
    answer: 2,
  },
  {
    id: "pool-squarecolor-116",
    cat: "rules",
    prompt: "What color is the square f1?",
    fen: "8/8/8/K7/8/8/3k4/8 w - - 0 1",
    options: ["Dark", "Light"],
    answer: 1,
  },
  {
    id: "pool-mobility-117",
    cat: "rules",
    prompt: "From this position, how many legal squares can the white bishop on b2 move to?",
    fen: "8/8/8/8/6k1/K7/1B6/8 w - - 0 1",
    options: ["10", "8", "2", "14"],
    answer: 1,
  },
  {
    id: "pool-hanging-118",
    cat: "tactics",
    prompt: "One piece on the board is attacked and has no defender. Which square is it on?",
    fen: "2k5/8/3q4/8/8/8/3R4/P1KQ4 w - - 0 1",
    options: ["d1", "d6", "a1", "d2"],
    answer: 1,
  },
  {
    id: "pool-promotion-119",
    cat: "endgame",
    prompt: "Can the White pawn on d7 promote by moving straight forward one square?",
    fen: "3n4/3P4/8/8/8/8/2K5/6k1 w - - 0 1",
    options: ["No", "Yes"],
    answer: 0,
  },
  {
    id: "pool-mostactive-120",
    cat: "positional",
    prompt: "Of the three white pieces on the board, which one currently has the most legal moves available?",
    fen: "2K5/8/3R4/5N2/5k2/8/8/B7 w - - 0 1",
    options: ["a1", "f5", "d6"],
    answer: 2,
  },
  {
    id: "pool-identify-121",
    cat: "rules",
    prompt: "What piece is on h7 in this position?",
    fen: "8/3K3R/8/8/8/8/3k4/8 w - - 0 1",
    options: ["Pawn", "Bishop", "Queen", "Rook"],
    answer: 3,
  },
  {
    id: "pool-squarecolor-122",
    cat: "rules",
    prompt: "What color is the square f6?",
    fen: "8/5K2/8/8/6k1/8/8/8 w - - 0 1",
    options: ["Dark", "Light"],
    answer: 0,
  },
  {
    id: "pool-mobility-123",
    cat: "rules",
    prompt: "From this position, how many legal squares can the white bishop on g7 move to?",
    fen: "8/6B1/8/8/8/8/8/1k4K1 w - - 0 1",
    options: ["11", "7", "13", "9"],
    answer: 3,
  },
  {
    id: "pool-hanging-124",
    cat: "tactics",
    prompt: "One piece on the board is attacked and has no defender. Which square is it on?",
    fen: "6rK/8/2b3B1/8/k7/1b3n2/8/8 w - - 0 1",
    options: ["c6", "g6", "b3", "f3"],
    answer: 1,
  },
  {
    id: "pool-promotion-125",
    cat: "endgame",
    prompt: "Can the Black pawn on a2 promote by moving straight forward one square?",
    fen: "1K6/8/8/8/5k2/8/p7/Q7 b - - 0 1",
    options: ["Yes", "No"],
    answer: 1,
  },
  {
    id: "pool-mostactive-126",
    cat: "positional",
    prompt: "Of the three white pieces on the board, which one currently has the most legal moves available?",
    fen: "4K3/7Q/4BQ2/8/8/8/3k4/8 w - - 0 1",
    options: ["e6", "h7", "f6"],
    answer: 1,
  },
  {
    id: "pool-identify-127",
    cat: "rules",
    prompt: "What piece is on h5 in this position?",
    fen: "8/8/8/7p/8/8/8/1K4k1 w - - 0 1",
    options: ["Knight", "Bishop", "Rook", "Pawn"],
    answer: 3,
  },
  {
    id: "pool-squarecolor-128",
    cat: "rules",
    prompt: "What color is the square g2?",
    fen: "8/2K5/8/8/8/8/8/k7 w - - 0 1",
    options: ["Dark", "Light"],
    answer: 1,
  },
  {
    id: "pool-mobility-129",
    cat: "rules",
    prompt: "From this position, how many legal squares can the white rook on h2 move to?",
    fen: "8/8/8/2K5/8/8/7R/4k3 w - - 0 1",
    options: ["14", "20", "12", "10"],
    answer: 0,
  },
  {
    id: "pool-hanging-130",
    cat: "tactics",
    prompt: "One piece on the board is attacked and has no defender. Which square is it on?",
    fen: "4b3/2K5/6r1/7B/8/7r/5r2/7k w - - 0 1",
    options: ["h5", "g6", "e8", "h3"],
    answer: 0,
  },
  {
    id: "pool-promotion-131",
    cat: "endgame",
    prompt: "Can the White pawn on c7 promote by moving straight forward one square?",
    fen: "2b5/1KP5/8/8/8/4k3/8/8 w - - 0 1",
    options: ["No", "Yes"],
    answer: 0,
  },
  {
    id: "pool-mostactive-132",
    cat: "positional",
    prompt: "Of the three white pieces on the board, which one currently has the most legal moves available?",
    fen: "2R5/8/4k3/6B1/8/8/R7/K7 w - - 0 1",
    options: ["c8", "g5", "a2"],
    answer: 0,
  },
  {
    id: "pool-identify-133",
    cat: "rules",
    prompt: "What piece is on d3 in this position?",
    fen: "8/8/8/7K/8/3b4/8/3k4 w - - 0 1",
    options: ["Knight", "Queen", "Bishop", "Rook"],
    answer: 2,
  },
  {
    id: "pool-squarecolor-134",
    cat: "rules",
    prompt: "What color is the square d8?",
    fen: "8/8/8/8/8/1K3k2/8/8 w - - 0 1",
    options: ["Dark", "Light"],
    answer: 0,
  },
  {
    id: "pool-hanging-136",
    cat: "tactics",
    prompt: "One piece on the board is attacked and has no defender. Which square is it on?",
    fen: "B7/8/8/8/7b/8/4r3/k2Kb3 w - - 0 1",
    options: ["e1", "a8", "h4", "e2"],
    answer: 3,
  },
  {
    id: "pool-mostactive-138",
    cat: "positional",
    prompt: "Of the three white pieces on the board, which one currently has the most legal moves available?",
    fen: "6N1/2k5/8/8/8/8/B6K/6Q1 w - - 0 1",
    options: ["g8", "g1", "a2"],
    answer: 1,
  },
];
